// app/layout.js (FINAL STRUCTURAL FIX)
import './globals.css';
import { CartProvider } from '../components/CartContext';
import CartDisplay from '../components/CartDisplay'; // 🚨 NEW IMPORT

export const metadata = {
  metadataBase: new URL('https://thetechshop.vercel.app'), // you can change domain later

  title: {
    default: 'TechyCity | Cheap Laptops & Gadgets in Ghana',
    template: '%s | TechyCity',
  },

  description:
    'TechyCity is your trusted store for cheap laptops in Ghana. Buy laptops for university students, office work, and professionals at affordable prices.',
  icons: {
  icon: '/favicon.ico', // Standard favicon (place in /app directory)
    shortcut: '/favicon-16x16.png', // Shortcut icon (optional, place in /public)
    apple: '/apple-touch-icon.png', // Apple touch icon (optional, place in /public)
    // Add other sizes or formats here if generated by a tool
  },
  
  keywords: [
    'cheap laptops in ghana',
    'laptops for university students',
    'affordable laptops ghana',
    'buy laptops in accra',
    'student laptops ghana',
    'techycity ghana',
    'budget laptops ghana',
  ],

  openGraph: {
    title: 'TechyCity | Cheap Laptops & Gadgets in Ghana',
    description:
      'Buy affordable laptops for students and professionals in Ghana at TechyCity.',
    url: 'https://thetechshop.vercel.app',
    siteName: 'TechyCity',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'TechyCity – Affordable Laptops in Ghana',
      },
    ],
    locale: 'en_GH',
    type: 'website',
  },

  twitter: {
    card: 'summary_large_image',
    title: 'TechyCity | Cheap Laptops in Ghana',
    description:
      'Affordable laptops for university students in Ghana.',
    images: ['/og-image.png'],
  },

  alternates: {
    canonical: 'https://thetechshop.vercel.app',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>

          <CartDisplay />
          
          {children}
          
        </CartProvider>
      </body>
    </html>
  );
}
